### ISSUE TITLE
Help! I always get the same error

### ISSUE THREAD

**Issue by sykesmarc** [bioinfo-tsukuba/CCPLS#1] opened 2023-06-19 14:44 UTC
Hello!

Thank you in advance you are taking your time to read my problem. I am basically working with spatial data and I'd like to use your library in R. The problem is that I always get the same issue, I have tried so many things, and nothings seems to work out. I have also compared multiple times with your example data, and I can not see any difference that could be the reason of my error. 

```
> result_CCPLS <- CCPLS::cellCellReg(exp_mat, coord_mat, annot_mat, output_dir, HVG_extract_num = 200)
[1] "=== cellCellRegMakeFet started... 2023-06-19 16:30:03 ==="
[1] "dist0 is... 18.79"
[1] "=== cellCellRegMakeFet finished... 2023-06-19 16:30:04 ==="
[1] "=========="
[1] "=== cellCellRegSepMat started... 2023-06-19 16:30:04 ==="
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |================================================================================================================================| 100%
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |================================================================================================================================| 100%
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |================================================================================================================================| 100%
Error in apply(exp_mat_sep_each, 1, sum) : 
  dim(X) must have a positive length
In addition: There were 16 warnings (use warnings() to see them)
```

I am currently working with 998 genes, and 2883 cells. My matrixes look like this:

- annotation matrix:

![Screenshot from 2023-06-19 16-38-45](https://github.com/bioinfo-tsukuba/CCPLS/assets/93338927/9c98a0a7-262b-4bfc-9d0c-2538b437c5a9)

- coordinates matrix

![Screenshot from 2023-06-19 16-39-41](https://github.com/bioinfo-tsukuba/CCPLS/assets/93338927/b2567fc1-5d37-47d9-98f4-63d1d4b26a5f)

- expression matrix

![Screenshot from 2023-06-19 16-40-33](https://github.com/bioinfo-tsukuba/CCPLS/assets/93338927/7681edfb-d5d6-48ac-a9ad-10585ab8a3e5)

Thank you so much in advance

-Marc

**Comment by t-takaho** [comment] 2023-06-20 03:20
Hello!

Thank you for using our tool. I'd like to fix bugs.

First, could you share the three matrices:
1. annotation matrix
2. coordinate matrix
3. expression matrix

if possible?

Second, please tell me the version of R you are using.

Sorry for the inconvenience.
Thank you so much in advance.

Takaho

**Comment by sykesmarc** [comment] 2023-06-20 08:38
Hello, thank you!

I am sharing this matrices with you:

1. Annotation matrix
[annot_mat.csv](https://github.com/bioinfo-tsukuba/CCPLS/files/11797869/annot_mat.csv)

2. Coordinate matrix
[coord_mat.csv](https://github.com/bioinfo-tsukuba/CCPLS/files/11797871/coord_mat.csv)

3.Expression matrix
[exp_mat.csv](https://github.com/bioinfo-tsukuba/CCPLS/files/11797872/exp_mat.csv)

I am using the version 4.1.2. 

Thank you again.

**Comment by t-takaho** [comment] 2023-06-20 23:58
Hello!

Thank you for sharing.
Please give me time to resolve the errors.

Thank you.

**Comment by t-takaho** [comment] 2023-07-03 06:45
Hello!

Sorry, it took so long.
Instead, I found the cause of the bugs and almost fixed them.

Please give me more time (ideally one week).

Thank you.

**Comment by t-takaho** [comment] 2023-07-04 03:59
Hello!

I was able to fix bugs earlier than expected.
I released the package as v0.1.1.
Could you reinstall our package CCPLS?

Then, please check if CCPLS works.

Best regards,
Takaho

**Comment by sykesmarc** [comment] 2023-07-05 07:29
Hello!

Thank you for taking your time fixing the bugs. I'll check if it works and I'll give you and update.

Thank you again for your help and support.

Marc

**Comment by sykesmarc** [comment] 2023-07-11 10:41
Hello!

I was able to run it with no problems. 

Thank you for fixing the bugs.

Marc

**Comment by t-takaho** [comment] 2023-07-12 00:29
Hello!

Thank you for your reply.

I'll close this issue.

Takaho

**Closed as completed by t-takaho** 2023-07-12 00:29 UTC
